### ISSUE TITLE
Type column query

### ISSUE THREAD

**Issue by mg2020git** [apascualgarcia/functionInk#6]
Hi Alberto! I can't seem to see where I've gone wrong with the 'type' column in functionInk (the issue where my types for ASV-ASV, ASV-partition, and partition-partition are seemingly not being differentiated when calculating structural equivalence). I've emailed you the input file and a screenshot of the line of code that runs functionInk - both seem to be fine as far as I can tell. The only thing that I can think of so far is that the names of the columns are different to those in the vignette, but I got the impression that the order of the columns is what is really important. Do you have any ideas?

**Comment by apascualgarcia** [comment]
Hi Matthew,

Your file has a problem easy to fix, you should either remove all quotes or at least the one in front of #, because this symbol introduces a commentary and, if you add a " in front of it the script, it will interpret that the name of the first node starts with #.

The other thing is that, since you are using the flag -w 0 it means that the file has no weights, but your file has weights (you fixed them yo one, but they are in the file). If you realize, when you run the code the output is:

```
>> Reading input arguments:
~~~ The network is weighted=1 or 2/unweighted=0? Value = 0
~~~ The network is directed=1/undirected=0? Value = 0
~~~ The network has different types=1/or a single type=0? Value = 1
~~~ The network file is = network_data_no_network.tsv
>> Processing input arguments:
~~~ Reading Node A from column 1
~~~ Reading Node B from column 2
~~~ Working with an unweighted network -- Jaccard Similarity
~~~ Working with a network with different types of links
~~~ **Reading types from column 3**

```
So it is reading the column that in your file has weights as the types column. In the script [documentation](https://apascualgarcia.github.io/functionInk/_pages/help/) you will find that:

```
If the network has no weights, either you use the general format (with -w 1) and all the weights are equal to one,
            or you use -w 0, and then the file can be simply formatted as:
                            NodeA   NodeB   Type
```
